version: 2
jobs:
  build:
    working_directory: ~/circleci-udacity-devops-microservices
    docker:
      - image: 'circleci/python:3.6.4'
    steps:
      - checkout
      - run:
          command: |
            make lint