version: 2
jobs:
  build:
    working_directory: ~/circleci-udacity-devops-microservices
    docker:
      - image: 'circleci/python:3.6.4'
    steps:
      - checkout
      - run:
          command: |
           # Install hadolint
           wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
           chmod +x /bin/hadolint
      - run:
          command: |
            make lint